#FROM registry.cn-shanghai.aliyuncs.com/odboy/kenaito-cicd:runtime-dotnet8-sdk
FROM mcr.microsoft.com/dotnet/aspnet:8.0

LABEL maintainer="tianjun@odboy.cn" \
      version="1.0.20260429" \
      description=".NET 8 Application Runtime Image - Daily Environment"

ENV TZ=Asia/Shanghai
# ASP.NET Core 内置的环境变量，用于标识应用运行的环境
ENV ASPNETCORE_ENVIRONMENT=Staging
# 应用端口
ENV SERVER_PORT=8000
# 暴露应用端口
EXPOSE ${SERVER_PORT}

WORKDIR /home/admin

COPY publish/ /home/admin/

RUN chmod +x /home/admin/*.dll || true

ENTRYPOINT ["dotnet", "kenaito-pilot.dll"]
