# ??????
mvnd.noBuffering=true
# ?????????????
mvnd.rollingWindowSize=0
# 7????????????????
mvnd.logPurgePeriod=7d
# 3??????????????????
mvnd.idleTimeout=3 hours
# ?????????????
mvnd.keepAlive=100 ms
# ??30????????????
mvnd.maxLostKeepAlive=30
# ???????????????????
mvnd.builder=smart
# Java????
java.home=/usr/local/java
# Maven ???? settings.xml ???
maven.settings=/usr/local/mvnd2/mvn/conf/settings.xml
