variables:
  # kenaito-pilot平台通过API传递过来的参数
  # 应用名称
  CONTEXT_NAME: "kenaito-pilot"
  # 版本号：格式yyyyMMddHHmmss
  VERSION_CODE: "default"
  # 环境编码：测试daily、预发stage、灰度gray、生产production
  ENV_CODE: "default"
  # 容器镜像服务
  CRI_SERVICE_ENDPOINT: "registry.cn-shanghai.aliyuncs.com"
  CRI_SERVICE_USER: "tianjun@odboy.cn"
  CRI_SERVICE_PWD: "1234567890"
  # 镜像名称
  IMAGE_NAME: "${CRI_SERVICE_ENDPOINT}/odboy/devops:${CONTEXT_NAME}_${ENV_CODE}_${VERSION_CODE}"

stages:
  - build

build:
  stage: build
  variables:
    projectId: $CI_PROJECT_ID
    projectName: $CI_PROJECT_NAME
    jobId: $CI_JOB_ID
    pipelineId: $CI_PIPELINE_ID
    commitId: $CI_COMMIT_SHA
  image: registry.cn-shanghai.aliyuncs.com/odboy/kenaito-cicd:runtime-go1.25.0
  tags:
    - builder
  only:
    - api
  script:
    - pwd
    - echo "开始构建"
    - GOOS=linux GOARCH=amd64 go build -o $CONTEXT_NAME main.go
    - echo "压缩构建产物"
    - tar -czvf ${CONTEXT_NAME}.tgz $CONTEXT_NAME
    - echo "根据dockerfile构建镜像"
    - buildah build -f Dockerfile_${ENV_CODE} -t $IMAGE_NAME .
    - echo "推送镜像到aliyun"
    - echo "$CRI_SERVICE_PWD" | buildah login --tls-verify=false -u $CRI_SERVICE_USER --password-stdin $CRI_SERVICE_ENDPOINT
    - buildah push --tls-verify=false $IMAGE_NAME
