FROM registry.cn-shanghai.aliyuncs.com/odboy/kenaito-cicd:runtime-springboot21

# 应用名称和环境变量
ENV APP_NAME=kenaito-pilot
ENV ENV_CODE=production

# 设置工作目录
WORKDIR /home/admin/${APP_NAME}

# 添加应用压缩包
ADD ${APP_NAME}.tgz .

